# -*- coding: utf-8 -*-
# Generated by Django 5.0.4 on 2024-04-25 13:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="tags",
        ),
    ]
