# -*- coding: utf-8 -*-
# Generated by Django 5.0.4 on 2024-04-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_remove_news_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="views",
            field=models.IntegerField(default=0),
        ),
    ]
